spring:
  application:
    name: yy_ai_agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ???
      chat:
        options:
          model: qwq-plus
    vectorstore:
      redis:
        initialize-schema: true
        index-name: assistant
        prefix: yy_ai_agent:vector_store
  data:
    redis:
      url: redis://localhost:6379
server:
  servlet:
    context-path: /api
  port: 8213

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yy.yy_ai_agent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

search-api:
  api-key: ???